version: '3.8'

services:
    user-service:
        build: ./user-service
        ports:
            - '3001:3001'
        environment:
            - PORT=3001

    order-service:
        build: ./order-service
        ports:
            - '3002:3002'
        environment:
            - PORT=3002
